export const books = [
    {
        name: 'Tales from Balladhoon',
        id: 'tales-from-balladhoon-2',
        image: 'tales-from-balladhoon-2.jpg',
        description: 'The <a href="#tales-from-balladhoon" class="link"><em>original Tales from Balladhoon</em></a>, reimagined, with more original stories!<hr />Join Johnny McGlory and his friends on a delightful journey through the Irish countryside, where fairies and leprechauns are as real as the donkey that walks under the sea and the magician who summons butterflies.<br /><br />These original Irish tales by Irish native Helen L. Williamson, are a delightful glimpse into the world of imagination and an introduction to the time honored craft of Irish storytelling. These books are sure to capture the hearts of both young and old.',
        paperback: true,
        paperbackPrice: 14.99,
        hardcover: true,
        hardcoverPrice: 23.99,
        pages: 92,
        width: 8,
        height: 10,
        published: 2022,
        publisher: 'Stratton Press',
        isbn: {
            10: '1648959520',
            13: '9781648959523',
        },
        urls: {
            'belle-isle': '',
            bookshop: 'https://bookshop.org/books/tales-from-balladhoon/9781648959509',
            'books-a-million': 'https://www.booksamillion.com/p/Helen-L-Williamson/9781648959523',
            'barnes-and-noble': 'https://www.barnesandnoble.com/w/tales-from-balladhoon-helen-l-williamson/1016491386',
            amazon: 'https://www.amazon.com/dp/1648959520',
        },
    },
    {
        name: 'Adventures in Dinglewood',
        id: 'adventures-in-dinglewood',
        image: 'adventures-in-dinglewood.jpg',
        description: "If you are in a hurry, you might pass by Dinglewood without paying much attention. But if you listen carefully, you just might hear the pitter-patter of small feet and the chattering of tiny voices. Turn the page—There's a world of adventure here in Dinglewood for you to discover!",
        paperback: true,
        paperbackPrice: 17.95,
        hardcover: true,
        hardcoverPrice: 26.95,
        pages: 80,
        width: 8.5,
        height: 8.5,
        published: 2018,
        publisher: 'Belle Isle Books',
        isbn: {
            10: '1947860216',
            13: '9781947860216',
        },
        urls: {
            'belle-isle': 'http://www.belleislebooks.com/store/p121/adventuresindinglewood.html',
            bookshop: 'https://bookshop.org/books/adventures-in-dinglewood/9781947860131',
            'books-a-million': 'https://www.booksamillion.com/p/9781947860131',
            'barnes-and-noble': 'https://www.barnesandnoble.com/w/adventures-in-dinglewood-helen-l-williamson/1129189888',
            amazon: 'https://www.amazon.com/dp/1947860216',
        },
    },
    {
        name: 'I Just Met a Dinosaur!',
        id: 'i-just-met-a-dinosaur',
        image: 'i-just-met-a-dinosaur.png',
        description: "If you met a dinosaur, what would you do? Play hide-and-seek or go to the zoo? Who knows if their skin was pink, purple, or blue? Or if they squawked, roared, or mooed? Did they polish their nails and feathers and scales, and sharpen their teeth with the ends of their tails? When you open this book of dinosaur rhymes, you'll meet some of those creatures from long-ago times!",
        paperback: false,
        hardcover: true,
        hardcoverPrice: 18.95,
        pages: 32,
        width: 11.25,
        height: 8.75,
        published: 2016,
        publisher: 'Belle Isle Books',
        isbn: {
            10: '1939930677',
            13: '9781939930675',
        },
        urls: {
            'belle-isle': 'http://www.belleislebooks.com/store/p93/I_Just_Met_a_Dinosaur!.html',
            bookshop: '',
            'barnes-and-noble': 'https://www.barnesandnoble.com/w/i-just-met-a-dinosaur-helen-l-williamson/1124812119',
            amazon: 'https://www.amazon.com/dp/1939930677',
        },
    },
    {
        name: 'Higgledy-Piggledy Thoughts',
        id: 'higgledy-piggledy-thoughts',
        image: 'higgledy-piggledy-thoughts.jpg',
        description: 'Have you thought of a goat . . .<br />. . . in a fancy coat?<br />Or a hen that could only <em>SNORE</em>?<br /><br />Children will enjoy and be inspired by many short poems and beautiful illustrations.',
        paperback: true,
        paperbackPrice: 12.95,
        hardcover: false,
        pages: 48,
        width: 8.5,
        height: 11,
        published: 2013,
        publisher: 'Donnan LLC',
        isbn: {
            10: '0981925235',
            13: '9780981925233',
        },
        urls: {
            'belle-isle': '',
            bookshop: '',
            'barnes-and-noble': '',
            amazon: 'https://www.amazon.com/dp/0981925235',
        },
    },
    {
        name: 'A Pineapple Dream and Other Nonsense',
        id: 'a-pineapple-dream-and-other-nonsense',
        image: 'a-pineapple-dream-and-other-nonsense.jpg',
        description: "A Pineapple Dream and Other Nonsense is a beautifully illustrated full-color book of poems. They will delight your child and encourage their imagination as they read or listen to the poems and see the detailed drawings.<br /><br />It's Nonsense, it's Fun,<br />It tickles you tongue.<br />There's a mouse that knits<br />And a cat that sits.<br />There's a whale you'll adore<br />And a whole lot more.<br /><br />So, my friends, find a cozy nook<br />And plunge headlong into this book.",
        paperback: true,
        paperbackPrice: 15.95,
        hardcover: false,
        pages: 40,
        width: 8.5,
        height: 11,
        published: 2011,
        publisher: 'Donnan LLC',
        isbn: {
            10: '0981925227',
            13: '9780981925226',
        },
        urls: {
            'belle-isle': '',
            bookshop: '',
            'barnes-and-noble': '',
            amazon: 'https://www.amazon.com/dp/0981925227',
        },
    },
    {
        name: 'Tales from Balladhoon',
        id: 'tales-from-balladhoon',
        image: 'tales-from-balladhoon.jpg',
        description: 'Join Johnny McGlory and his friends on a delightful journey through the Irish countryside, where fairies and leprechauns are as real as the donkey that walks under the sea and the magician who summons butterflies.<br /><br />These original Irish tales by Irish native Helen L. Williamson, are a delightful glimpse into the world of imagination and an introduction to the time honored craft of Irish storytelling. These books are sure to capture the hearts of both young and old.',
        paperback: true,
        paperbackPrice: 12.95,
        hardcover: false,
        pages: 87,
        width: 6,
        height: 9,
        published: 2008,
        publisher: 'Donnan LLC',
        isbn: {
            10: '0981925200',
            13: '9780981925202',
        },
        urls: {
            'belle-isle': '',
            bookshop: '',
            'barnes-and-noble': '',
            amazon: 'https://www.amazon.com/dp/0981925200',
        },
    },
];
